# basic options
title: Research roundup
author: John Boniello
email: johnboniello@gmail.com
description: Research roundup
twitter_username: johnboniello
github_username:  johnboniello


# Build settings
markdown: kramdown
theme: minima
